"""add layer status fields to jobs

Revision ID: 68d84006fdb1
Revises: 80f37cc4c47e
Create Date: 2026-02-17 15:32:07.761238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68d84006fdb1'
down_revision: Union[str, None] = '80f37cc4c47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_email', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('layer1_status', sa.String(length=20), nullable=False, server_default='idle'))
    op.add_column('jobs', sa.Column('layer1_completed_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('layer2_status', sa.String(length=20), nullable=False, server_default='idle'))
    op.add_column('jobs', sa.Column('layer2_completed_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('layer3_status', sa.String(length=20), nullable=False, server_default='idle'))
    op.add_column('jobs', sa.Column('layer3_completed_at', sa.DateTime(), nullable=True))
    op.add_column('leads', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('reviews_per_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('leads', sa.Column('primary_email', sa.String(length=320), nullable=True))
    op.add_column('leads', sa.Column('emails', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('leads', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('leads', sa.Column('owner_name', sa.String(length=300), nullable=True))
    op.add_column('leads', sa.Column('employee_count', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('year_established', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('business_age_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'business_age_years')
    op.drop_column('leads', 'year_established')
    op.drop_column('leads', 'employee_count')
    op.drop_column('leads', 'owner_name')
    op.drop_column('leads', 'social_links')
    op.drop_column('leads', 'emails')
    op.drop_column('leads', 'primary_email')
    op.drop_column('leads', 'reviews_per_score')
    op.drop_column('leads', 'verified')
    op.drop_column('leads', 'description')
    op.drop_column('jobs', 'layer3_completed_at')
    op.drop_column('jobs', 'layer3_status')
    op.drop_column('jobs', 'layer2_completed_at')
    op.drop_column('jobs', 'layer2_status')
    op.drop_column('jobs', 'layer1_completed_at')
    op.drop_column('jobs', 'layer1_status')
    op.drop_column('jobs', 'user_email')
    # ### end Alembic commands ###
