"""create tables

Revision ID: 80f37cc4c47e
Revises: 
Create Date: 2026-02-16 12:15:20.197093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80f37cc4c47e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'geocoding', 'grid_search', 'playwright', 'serp_api', 'dedup', 'enriching', 'completed', 'failed', 'cancelled', name='job_status', create_constraint=True), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('total_found', sa.Integer(), nullable=False),
    sa.Column('total_unique', sa.Integer(), nullable=False),
    sa.Column('places_api_calls', sa.Integer(), nullable=False),
    sa.Column('serp_api_calls', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('business_type', sa.String(length=200), nullable=True),
    sa.Column('types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('business_status', sa.String(length=50), nullable=True),
    sa.Column('maps_url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_job_id'), 'leads', ['job_id'], unique=False)
    op.create_index('ix_leads_job_id_place_id', 'leads', ['job_id', 'place_id'], unique=True)
    op.create_index('ix_leads_name', 'leads', ['name'], unique=False)
    op.create_index(op.f('ix_leads_place_id'), 'leads', ['place_id'], unique=False)
    op.create_index('ix_leads_rating', 'leads', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leads_rating', table_name='leads')
    op.drop_index(op.f('ix_leads_place_id'), table_name='leads')
    op.drop_index('ix_leads_name', table_name='leads')
    op.drop_index('ix_leads_job_id_place_id', table_name='leads')
    op.drop_index(op.f('ix_leads_job_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_created_at', table_name='jobs')
    op.drop_table('jobs')
    op.execute("DROP TYPE IF EXISTS job_status")
    # ### end Alembic commands ###
