"""add batches and email fields

Revision ID: a23a8632738d
Revises: b4b4d9c00244
Create Date: 2026-02-18 08:21:04.647997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23a8632738d'
down_revision: Union[str, None] = 'b4b4d9c00244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('completed_jobs', sa.Integer(), nullable=False),
    sa.Column('failed_jobs', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_index('ix_jobs_batch_id', 'jobs', ['batch_id'], unique=False)
    op.create_foreign_key(
        'fk_jobs_batch_id_batches',
        'jobs',
        'batches',
        ['batch_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_batch_id_batches', 'jobs', type_='foreignkey')
    op.drop_index('ix_jobs_batch_id', table_name='jobs')
    op.drop_column('jobs', 'batch_id')
    op.drop_table('batches')
    # ### end Alembic commands ###
