"""add lead management fields

Revision ID: e31739a346be
Revises: a23a8632738d
Create Date: 2026-02-22 11:33:12.096179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e31739a346be'
down_revision: Union[str, None] = 'a23a8632738d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('leads', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('leads', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_leads_is_favorite'), 'leads', ['is_favorite'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_is_favorite'), table_name='leads')
    op.drop_column('leads', 'tags')
    op.drop_column('leads', 'notes')
    op.drop_column('leads', 'is_archived')
    op.drop_column('leads', 'is_favorite')
    # ### end Alembic commands ###
